package handlers

import (
	"crypto/rand"
	"database/sql"
	"fmt"
	"math/big"
	"net/http"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/lib/pq"
	"github.com/minio/minio-go/v7"

	"nu-housing-management-system/backend/internal/auth"
	"nu-housing-management-system/backend/internal/database"
	"nu-housing-management-system/backend/internal/models"
	"strings"
)

//////////////////////////////////////////////////////////
// AUTH HANDLERS
//////////////////////////////////////////////////////////

func Register(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var user struct {
			NuID            string `json:"nu_id"`
			FirstName       string `json:"firstName"`
			LastName        string `json:"lastName"`
			Email           string `json:"email" binding:"required,email"`
			Password        string `json:"password" binding:"required,min=6"`
			ConfirmPassword string `json:"confirmPassword"`
			Phone           string `json:"phone"`
			Role            string `json:"role"`
		}
		if err := c.ShouldBindJSON(&user); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		if user.ConfirmPassword != "" && user.Password != user.ConfirmPassword {
			c.JSON(http.StatusBadRequest, gin.H{"error": "passwords do not match"})
			return
		}

		role := strings.ToLower(user.Role)
		if role == "" {
			role = "student"
		}

		if role != "student" && role != "housing" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role: only 'student' or 'housing' allowed"})
			return
		}

		nuID := strings.TrimSpace(user.NuID)
		autoGeneratedNuID := nuID == ""
		if autoGeneratedNuID {
			nuID = generateFallbackNuID()
		}

		roleID, err := database.GetRoleIDByName(db, role)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "role lookup failed"})
			return
		}

		if _, err := database.GetUserByEmail(db, user.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}

		hashed, err := auth.HashPassword(user.Password)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to hash password"})
			return
		}

		u := models.User{
			NuID:         nuID,
			Email:        user.Email,
			PasswordHash: hashed,
			RoleID:       roleID,
			Phone:        &user.Phone,
		}
		id := 0
		for attempt := 0; attempt < 20; attempt++ {
			if autoGeneratedNuID && attempt > 0 {
				u.NuID = generateFallbackNuID()
			}

			id, err = database.CreateUser(db, u)
			if err == nil {
				break
			}

			if autoGeneratedNuID {
				if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" && pqErr.Constraint == "users_nu_id_key" {
					continue
				}
			}

			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": err.Error()})
			return
		}
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": "could not generate a unique student id"})
			return
		}

		// log registration
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'register', 'user', $1)`, id)

		c.JSON(http.StatusCreated, gin.H{"userId": id})
	}
}

func generateFallbackNuID() string {
	const (
		minSubmissionYear = 2018
		maxSubmissionYear = 2024
	)

	yearSpan := int64(maxSubmissionYear - minSubmissionYear + 1)
	yearOffset, err := rand.Int(rand.Reader, big.NewInt(yearSpan))
	if err != nil {
		return "202400000"
	}

	suffix, err := rand.Int(rand.Reader, big.NewInt(100000))
	if err != nil {
		return "202400000"
	}

	year := minSubmissionYear + int(yearOffset.Int64())
	return fmt.Sprintf("%04d%05d", year, suffix.Int64())
}

func Login(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			Email    string `json:"email" binding:"required,email"`
			Password string `json:"password" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}

		user, err := database.ValidateUserCredentials(db, body.Email)
		if err != nil {
			// log failed login — no actor_id since user not found
			db.Exec(`INSERT INTO audit_logs (action, entity) VALUES ('login_failed', 'user')`)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "no such email exists"})
			return
		}

		if err := auth.CheckPassword(user.PasswordHash, body.Password); err != nil {
			// log failed login — we know the user but wrong password
			db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login_failed', 'user', $1)`, user.ID)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "wrong password"})
			return
		}

		roleName, _ := database.GetRoleNameByID(db, user.RoleID)

		token, err := auth.GenerateToken(user.ID, roleName)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "token generation failed"})
			return
		}

		// log successful login
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login', 'user', $1)`, user.ID)

		c.JSON(http.StatusOK, gin.H{
			"token": token,
			"user": gin.H{
				"id":    user.ID,
				"nu_id": user.NuID,
				"email": user.Email,
				"role":  roleName,
				"phone": user.Phone,
			},
		})
	}
}

//////////////////////////////////////////////////////////
// APPLICATION HANDLERS
//////////////////////////////////////////////////////////

func SubmitApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			Year           int    `json:"year" binding:"required"`
			Major          string `json:"major" binding:"required"`
			Gender         string `json:"gender" binding:"required"`
			RoomPreference string `json:"room_preference"`
			AdditionalInfo string `json:"additional_info"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		app := models.Application{
			StudentID:      studentID,
			Year:           body.Year,
			Major:          body.Major,
			Gender:         body.Gender,
			RoomPreference: body.RoomPreference,
			AdditionalInfo: body.AdditionalInfo,
		}

		id, err := database.SubmitApplication(db, app)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to submit application", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"application_id": id})
	}
}

func GetMyApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		apps, err := database.GetApplicationsByStudent(db, studentID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch applications", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, apps)
	}
}

func GetApplicationStatus(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		app, err := database.GetApplicationByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": app.Status, "rejected_reason": app.RejectedReason})
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLERS
//////////////////////////////////////////////////////////

func UploadDocument(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		applicationID, err := strconv.Atoi(c.PostForm("application_id"))
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_id"})
			return
		}

		docType := c.PostForm("type")
		if docType == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "type is required"})
			return
		}

		file, err := c.FormFile("file")
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "file is required"})
			return
		}

		if !strings.HasSuffix(file.Filename, ".pdf") {
			c.JSON(http.StatusBadRequest, gin.H{"error": "only PDF files are allowed"})
			return
		}

		fileObj, err := file.Open()
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to open file"})
			return
		}
		defer fileObj.Close()

		objectName := fmt.Sprintf("applications/%d/%s.pdf", applicationID, docType)
		_, err = minioStore.Client.PutObject(c, minioStore.Bucket, objectName, fileObj, file.Size, minio.PutObjectOptions{ContentType: "application/pdf"})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to upload to storage", "details": err.Error()})
			return
		}

		doc := models.Document{
			ApplicationID: applicationID,
			Type:          docType,
			FileURL:       objectName,
		}
		id, err := database.InsertDocument(db, doc)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to save document into db", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"document_id": id})
	}
}

func GetDocument(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("doc_id")
		id, _ := strconv.Atoi(idStr)
		doc, err := database.GetDocument(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document not found"})
			return
		}
		c.JSON(http.StatusOK, doc)
	}
}

//////////////////////////////////////////////////////////
// HOUSING STAFF HANDLERS
//////////////////////////////////////////////////////////

func HousingListApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		apps, err := database.HousingListApplications(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list applications", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, apps)
	}
}

func HousingGetApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		app, err := database.HousingGetApplication(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		c.JSON(http.StatusOK, app)
	}
}

func HousingApprove(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingApprove(db, id, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "approve failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "approved"})
	}
}

func HousingReject(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		var body struct {
			Reason string `json:"reason" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "reason is required"})
			return
		}
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingReject(db, id, body.Reason, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "reject failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "rejected"})
	}
}

//////////////////////////////////////////////////////////
// ADMIN HANDLERS
//////////////////////////////////////////////////////////

func AdminListUsers(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		users, err := database.ListUsers(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list users"})
			return
		}
		c.JSON(http.StatusOK, users)
	}
}

func AdminCreateUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			NuID  string `json:"nu_id" binding:"required"`
			Email string `json:"email" binding:"required,email"`
			Phone string `json:"phone"`
			Role  string `json:"role" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}
		roleID, err := database.GetRoleIDByName(db, body.Role)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role"})
			return
		}
		if _, err := database.GetUserByEmail(db, body.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}
		u := models.User{
			NuID:         body.NuID,
			Email:        strings.ToLower(strings.TrimSpace(body.Email)),
			PasswordHash: "",
			RoleID:       roleID,
			Phone:        &body.Phone,
		}
		id, err := database.CreateUser(db, u)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "create user failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"id": id})
	}
}

func AdminDeleteUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		if err := database.DeleteUser(db, id); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "delete failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "deleted"})
	}
}

func AdminSystemLogs(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		logs, err := database.AdminSystemLogs(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch logs"})
			return
		}
		c.JSON(http.StatusOK, logs)
	}
}

func AdminStats(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		stats, err := database.AdminStats(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch stats"})
			return
		}
		c.JSON(http.StatusOK, stats)
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLER
//////////////////////////////////////////////////////////

func GetDocumentsByApplication(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("app_id")
		appID, _ := strconv.Atoi(idStr)

		docs, err := database.GetDocumentsByApplication(db, appID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch documents"})
			return
		}

		type DocResponse struct {
			ID          int    `json:"id"`
			Type        string `json:"type"`
			DownloadURL string `json:"download_url"`
		}

		var result []DocResponse
		for _, doc := range docs {
			url, err := minioStore.PresignClient.PresignedGetObject(
				c,
				minioStore.Bucket,
				doc.FileURL,
				24*time.Hour,
				nil,
			)
			if err != nil {
				continue
			}

			result = append(result, DocResponse{
				ID:          doc.ID,
				Type:        doc.Type,
				DownloadURL: url.String(),
			})
		}

		if result == nil {
			result = []DocResponse{}
		}

		c.JSON(http.StatusOK, result)
	}
}
