package handlers

import (
	"bytes"
	"context"
	"crypto/rand"
	"database/sql"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"nu-housing-management-system/backend/internal/analysis"
	"nu-housing-management-system/backend/internal/auth"
	"nu-housing-management-system/backend/internal/config"
	"nu-housing-management-system/backend/internal/database"
	"nu-housing-management-system/backend/internal/models"
	"nu-housing-management-system/backend/internal/notifications"

	"github.com/gin-gonic/gin"
	"github.com/lib/pq"
	"github.com/minio/minio-go/v7"
	"github.com/spf13/viper"
)

//////////////////////////////////////////////////////////
// AUTH HANDLERS
//////////////////////////////////////////////////////////

func Register(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var user struct {
			NuID            string `json:"nu_id"`
			FirstName       string `json:"firstName"`
			LastName        string `json:"lastName"`
			Email           string `json:"email" binding:"required,email"`
			Password        string `json:"password" binding:"required,min=6"`
			ConfirmPassword string `json:"confirmPassword"`
			Phone           string `json:"phone"`
			Role            string `json:"role"`
		}
		if err := c.ShouldBindJSON(&user); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		if user.ConfirmPassword != "" && user.Password != user.ConfirmPassword {
			c.JSON(http.StatusBadRequest, gin.H{"error": "passwords do not match"})
			return
		}

		role := strings.ToLower(user.Role)
		if role == "" {
			role = "student"
		}

		if role != "student" && role != "housing" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role: only 'student' or 'housing' allowed"})
			return
		}

		nuID := strings.TrimSpace(user.NuID)
		autoGeneratedNuID := nuID == ""
		if autoGeneratedNuID {
			nuID = generateFallbackNuID()
		}

		roleID, err := database.GetRoleIDByName(db, role)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "role lookup failed"})
			return
		}

		if _, err := database.GetUserByEmail(db, user.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}

		hashed, err := auth.HashPassword(user.Password)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to hash password"})
			return
		}

		u := models.User{
			NuID:         nuID,
			Email:        user.Email,
			PasswordHash: hashed,
			RoleID:       roleID,
			Phone:        &user.Phone,
		}
		id := 0
		for attempt := 0; attempt < 20; attempt++ {
			if autoGeneratedNuID && attempt > 0 {
				u.NuID = generateFallbackNuID()
			}

			id, err = database.CreateUser(db, u)
			if err == nil {
				break
			}

			if autoGeneratedNuID {
				if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" && pqErr.Constraint == "users_nu_id_key" {
					continue
				}
			}

			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": err.Error()})
			return
		}
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": "could not generate a unique student id"})
			return
		}

		// log registration
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'register', 'user', $1)`, id)

		c.JSON(http.StatusCreated, gin.H{"userId": id})
	}
}

func generateFallbackNuID() string {
	const (
		minSubmissionYear = 2018
		maxSubmissionYear = 2024
	)

	yearSpan := int64(maxSubmissionYear - minSubmissionYear + 1)
	yearOffset, err := rand.Int(rand.Reader, big.NewInt(yearSpan))
	if err != nil {
		return "202400000"
	}

	suffix, err := rand.Int(rand.Reader, big.NewInt(100000))
	if err != nil {
		return "202400000"
	}

	year := minSubmissionYear + int(yearOffset.Int64())
	return fmt.Sprintf("%04d%05d", year, suffix.Int64())
}

func Login(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			Email    string `json:"email" binding:"required,email"`
			Password string `json:"password" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}

		user, err := database.ValidateUserCredentials(db, body.Email)
		if err != nil {
			// log failed login — no actor_id since user not found
			db.Exec(`INSERT INTO audit_logs (action, entity) VALUES ('login_failed', 'user')`)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "no such email exists"})
			return
		}

		if err := auth.CheckPassword(user.PasswordHash, body.Password); err != nil {
			// log failed login — we know the user but wrong password
			db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login_failed', 'user', $1)`, user.ID)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "wrong password"})
			return
		}

		roleName, _ := database.GetRoleNameByID(db, user.RoleID)

		token, err := auth.GenerateToken(user.ID, roleName)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "token generation failed"})
			return
		}

		// log successful login
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login', 'user', $1)`, user.ID)

		c.JSON(http.StatusOK, gin.H{
			"token": token,
			"user": gin.H{
				"id":    user.ID,
				"nu_id": user.NuID,
				"email": user.Email,
				"role":  roleName,
				"phone": user.Phone,
			},
		})
	}
}

//////////////////////////////////////////////////////////
// APPLICATION HANDLERS
//////////////////////////////////////////////////////////

func SubmitApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			ApplicantType  string `json:"applicant_type"`
			StudentNumber  string `json:"student_number"`
			NameSurname    string `json:"name_surname"`
			FIO            string `json:"fio"`
			BirthDate      string `json:"birth_date"`
			IIN            string `json:"iin"`
			School         string `json:"school"`
			Level          string `json:"level"`
			PassportNumber string `json:"passport_number"`
			Comments       string `json:"comments"`
			Year           int    `json:"year" binding:"required"`
			Major          string `json:"major" binding:"required"`
			Gender         string `json:"gender" binding:"required"`
			RoomPreference string `json:"room_preference"`
			AdditionalInfo string `json:"additional_info"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		parseBirthDate := func(raw string) (*time.Time, bool) {
			rawBirthDate := strings.TrimSpace(raw)
			if rawBirthDate == "" {
				return nil, true
			}
			parsed, err := time.Parse("2006-01-02", rawBirthDate)
			if err != nil {
				return nil, false
			}
			return &parsed, true
		}

		birthDate, ok := parseBirthDate(body.BirthDate)
		if !ok {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid birth_date", "details": "expected YYYY-MM-DD"})
			return
		}

		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load application settings", "details": err.Error()})
			return
		}
		if !database.IsApplicationsOpen(settings, time.Now()) {
			c.JSON(http.StatusForbidden, gin.H{
				"error":                "applications are currently closed",
				"applications_enabled": settings.ApplicationsEnabled,
				"application_open":     formatDatePtr(settings.ApplicationOpen),
				"application_close":    formatDatePtr(settings.ApplicationClose),
			})
			return
		}

		app := models.Application{
			StudentID:      studentID,
			ApplicantType:  database.NormalizeApplicantTypeForSubmission(body.ApplicantType, body.AdditionalInfo),
			StudentNumber:  strings.TrimSpace(body.StudentNumber),
			NameSurname:    strings.TrimSpace(body.NameSurname),
			FIO:            strings.TrimSpace(body.FIO),
			BirthDate:      birthDate,
			IIN:            strings.TrimSpace(body.IIN),
			School:         strings.TrimSpace(body.School),
			Level:          strings.TrimSpace(body.Level),
			PassportNumber: strings.TrimSpace(body.PassportNumber),
			Comments:       strings.TrimSpace(body.Comments),
			Year:           body.Year,
			Major:          body.Major,
			Gender:         body.Gender,
			RoomPreference: body.RoomPreference,
			AdditionalInfo: body.AdditionalInfo,
		}
		if app.FIO == "" {
			app.FIO = database.ExtractFIOForSubmission(body.AdditionalInfo)
		}
		if app.NameSurname == "" {
			app.NameSurname = database.ExtractNameSurnameForSubmission(body.AdditionalInfo)
		}
		if app.NameSurname == "" {
			app.NameSurname = app.FIO
		}
		if app.StudentNumber == "" {
			app.StudentNumber = database.ExtractStudentNumberForSubmission(body.AdditionalInfo)
		}
		if app.BirthDate == nil {
			extractedBirthDate := database.ExtractBirthDateForSubmission(body.AdditionalInfo)
			parsedBirthDate, ok := parseBirthDate(extractedBirthDate)
			if !ok {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid birth_date", "details": "expected YYYY-MM-DD"})
				return
			}
			app.BirthDate = parsedBirthDate
		}
		if app.IIN == "" {
			app.IIN = database.ExtractIINForSubmission(body.AdditionalInfo)
		}
		if app.School == "" {
			app.School = database.ExtractSchoolForSubmission(body.AdditionalInfo)
		}
		if app.Level == "" {
			app.Level = database.ExtractLevelForSubmission(body.AdditionalInfo)
		}
		if app.PassportNumber == "" {
			app.PassportNumber = database.ExtractPassportNumberForSubmission(body.AdditionalInfo)
		}

		id, err := database.SubmitApplication(db, app)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to submit application", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"application_id": id})
	}
}

func GetMyApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		apps, err := database.GetApplicationsByStudent(db, studentID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch applications", "details": err.Error()})
			return
		}
		roomAllocations, err := listRoomAllocationPayloads(db, apps)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch room allocations", "details": err.Error()})
			return
		}
		response := make([]gin.H, 0, len(apps))
		for _, app := range apps {
			response = append(response, buildBasicApplicationPayloadWithRoom(app, "", roomAllocations[app.ID]))
		}
		c.JSON(http.StatusOK, response)
	}
}

func UpdateMyApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := strconv.Atoi(c.Param("id"))
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application id"})
			return
		}

		var body struct {
			ApartmentInAstana   *bool   `json:"apartment_in_astana"`
			ParentsWorkInAstana *bool   `json:"parents_work_in_astana"`
			AstanaResident      *bool   `json:"astana_resident"`
			PreferredRoommate   *string `json:"preferred_roommate"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		app, err := database.GetApplicationByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		if app.StudentID != studentID {
			c.JSON(http.StatusForbidden, gin.H{"error": "access denied"})
			return
		}

		app.AdditionalInfo = mergeEditableApplicationDetails(
			app.AdditionalInfo,
			body.ApartmentInAstana,
			body.ParentsWorkInAstana,
			body.AstanaResident,
			body.PreferredRoommate,
		)

		updated, err := database.UpdateStudentApplicationDetails(db, studentID, app)
		if err != nil {
			if err.Error() == "application not found" {
				c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
				return
			}
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update application", "details": err.Error()})
			return
		}

		payload, err := buildApplicationReviewPayload(db, updated)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch application review details", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, payload)
	}
}

func GetApplicationStatus(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, err := strconv.Atoi(idStr)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application id"})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		app, err := database.GetApplicationByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		if app.StudentID != studentID {
			c.JSON(http.StatusForbidden, gin.H{"error": "access denied"})
			return
		}
		roomAllocation := lookupRoomAllocationPayload(db, app.ID)
		c.JSON(http.StatusOK, gin.H{
			"status":          app.Status,
			"is_approved":     strings.EqualFold(strings.TrimSpace(app.Status), "approved"),
			"reason":          app.DecisionReason,
			"decision_reason": app.DecisionReason,
			"rejected_reason": app.RejectedReason,
			"room_allocation": roomAllocation,
			"room":            roomLabelFromPayload(roomAllocation),
		})
	}
}

func GetSystemSettings(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch system settings", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, buildSystemSettingsResponse(settings))
	}
}

func UpdateSystemSettings(db *sql.DB, cfg *config.Config) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			ApplicationsEnabled *bool     `json:"applications_enabled"`
			ApplicationOpen     *string   `json:"application_open"`
			ApplicationClose    *string   `json:"application_close"`
			RequiredDocuments   *[]string `json:"required_documents"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load current settings", "details": err.Error()})
			return
		}
		wasApplicationsEnabled := settings.ApplicationsEnabled
		var emailResult *applicationEmailResult

		if body.ApplicationsEnabled != nil {
			settings.ApplicationsEnabled = *body.ApplicationsEnabled
		}

		if body.ApplicationOpen != nil {
			parsedDate, err := parseDateField(*body.ApplicationOpen)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_open", "details": "expected YYYY-MM-DD or empty string"})
				return
			}
			settings.ApplicationOpen = parsedDate
		}

		if body.ApplicationClose != nil {
			parsedDate, err := parseDateField(*body.ApplicationClose)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_close", "details": "expected YYYY-MM-DD or empty string"})
				return
			}
			settings.ApplicationClose = parsedDate
		}

		if settings.ApplicationOpen != nil && settings.ApplicationClose != nil && settings.ApplicationClose.Before(*settings.ApplicationOpen) {
			c.JSON(http.StatusBadRequest, gin.H{"error": "application_close must be on or after application_open"})
			return
		}

		if body.RequiredDocuments != nil {
			settings.RequiredDocuments = *body.RequiredDocuments
		}
		if settings.RequiredDocuments == nil {
			settings.RequiredDocuments = []string{}
		}

		settings, err = database.UpdateSystemSettings(db, settings)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update system settings", "details": err.Error()})
			return
		}
		if wasApplicationsEnabled && !settings.ApplicationsEnabled {
			if err := database.RunRoomAllocation(db); err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "applications were closed but room allocation failed", "details": err.Error()})
				return
			}
			recipients, err := database.ListApplicationNotificationRecipients(db)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "applications were closed but notification recipients could not be loaded", "details": err.Error()})
				return
			}
			if err := database.InsertApplicationClosureNotifications(db, recipients); err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "applications were closed but notifications could not be created", "details": err.Error()})
				return
			}
			result := sendApplicationClosureEmails(cfg, recipients)
			if result.Failed > 0 {
				c.JSON(http.StatusInternalServerError, gin.H{
					"error":                       "applications were closed but some email notifications failed",
					"email_notifications_sent":    result.Sent,
					"email_notifications_failed":  result.Failed,
					"email_notifications_skipped": result.Skipped,
					"details":                     result.Errors,
				})
				return
			}
			emailResult = &result
		}

		if userID, _, ok := requestIdentity(c); ok {
			db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'update_settings', 'system_settings', $2)`, userID, settings.ID)
		}

		response := buildSystemSettingsResponse(settings)
		if emailResult != nil {
			response["email_notifications_sent"] = emailResult.Sent
			response["email_notifications_failed"] = emailResult.Failed
			response["email_notifications_skipped"] = emailResult.Skipped
		}
		c.JSON(http.StatusOK, response)
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLERS
//////////////////////////////////////////////////////////

func UploadDocument(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		applicationID, err := strconv.Atoi(c.PostForm("application_id"))
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_id"})
			return
		}

		docType := c.PostForm("type")
		if docType == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "type is required"})
			return
		}

		file, err := c.FormFile("file")
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "file is required"})
			return
		}

		if !strings.EqualFold(filepath.Ext(file.Filename), ".pdf") {
			c.JSON(http.StatusBadRequest, gin.H{"error": "only PDF files are allowed"})
			return
		}

		fileObj, err := file.Open()
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to open file"})
			return
		}
		defer fileObj.Close()

		if !authorizeApplicationAccess(c, db, applicationID) {
			return
		}

		pdfBytes, err := io.ReadAll(fileObj)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to read file"})
			return
		}

		contentType := file.Header.Get("Content-Type")
		if contentType == "" {
			contentType = "application/pdf"
		}

		objectName := fmt.Sprintf("applications/%d/%s.pdf", applicationID, docType)
		_, err = minioStore.Client.PutObject(
			c,
			minioStore.Bucket,
			objectName,
			bytes.NewReader(pdfBytes),
			int64(len(pdfBytes)),
			minio.PutObjectOptions{ContentType: contentType},
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to upload to storage", "details": err.Error()})
			return
		}

		originalFilename := file.Filename
		doc := models.Document{
			ApplicationID:    applicationID,
			Type:             docType,
			FileURL:          objectName,
			OriginalFilename: &originalFilename,
			ContentType:      &contentType,
		}
		id, err := database.SaveDocumentReplacingType(db, doc)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to save document into db", "details": err.Error()})
			return
		}

		go processUploadedDocumentAsync(db, applicationID, id, docType, append([]byte(nil), pdfBytes...))
		c.JSON(http.StatusCreated, gin.H{"document_id": id})
	}
}

func processUploadedDocumentAsync(db *sql.DB, applicationID, documentID int, docType string, pdfBytes []byte) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	if err := analyzeAndApplyDecision(ctx, db, applicationID, documentID, docType, pdfBytes); err != nil {
		fmt.Printf("background document analysis failed for application %d document %d: %v\n", applicationID, documentID, err)
	}
}

func analyzeAndApplyDecision(ctx context.Context, db *sql.DB, applicationID, documentID int, docType string, pdfBytes []byte) error {
	expectedType, ok := analysis.NormalizeDocumentType(docType)
	if !ok {
		result := analysis.ManualReviewResult(
			analysis.Request{
				DocumentID: documentID,
				Application: analysis.ApplicationContext{
					ApplicationID: applicationID,
				},
			},
			"",
			fmt.Sprintf("Manual review required because the uploaded document type %q is not supported for automatic Astana checks.", docType),
			"unsupported_document_type",
		)
		if err := database.UpsertDocumentAnalysis(db, result); err != nil {
			return err
		}
		return database.ApplyAutomatedDecision(db, applicationID)
	}

	app, err := database.GetApplicationByID(db, applicationID)
	if err != nil {
		return err
	}
	user, err := database.GetUserByID(db, app.StudentID)
	if err != nil {
		return err
	}

	analyzer := analysis.NewOpenAIAnalyzer(viper.GetString("OPENAI_API_KEY"), viper.GetString("OPENAI_MODEL"))
	req := analysis.Request{
		DocumentID:   documentID,
		ExpectedType: expectedType,
		PDFBytes:     pdfBytes,
		Application: analysis.ApplicationContext{
			ApplicationID:  app.ID,
			StudentID:      app.StudentID,
			StudentEmail:   user.Email,
			StudentNuID:    user.NuID,
			ApplicantType:  app.ApplicantType,
			StudentFIO:     app.FIO,
			PassportNumber: app.PassportNumber,
			Year:           app.Year,
			Major:          app.Major,
			Gender:         app.Gender,
			RoomPreference: app.RoomPreference,
			AdditionalInfo: app.AdditionalInfo,
			SubmittedAt:    app.SubmittedAt,
			UploadTime:     time.Now().UTC(),
		},
	}

	result, analyzeErr := analyzer.AnalyzeDocument(ctx, req)
	if err := database.UpsertDocumentAnalysis(db, result); err != nil {
		return err
	}
	if err := database.ApplyAutomatedDecision(db, applicationID); err != nil {
		return err
	}
	if analyzeErr != nil {
		return nil
	}
	return nil
}

func GetDocument(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("doc_id")
		id, _ := strconv.Atoi(idStr)
		doc, err := database.GetDocument(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document not found"})
			return
		}

		if !authorizeApplicationAccess(c, db, doc.ApplicationID) {
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"id":                doc.ID,
			"application_id":    doc.ApplicationID,
			"type":              doc.Type,
			"original_filename": doc.OriginalFilename,
			"mime_type":         doc.ContentType,
			"uploaded_at":       doc.UploadedAt,
			"download_url":      buildDocumentDownloadURL(c, doc.ID),
		})
	}
}

func DownloadDocument(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("doc_id")
		id, _ := strconv.Atoi(idStr)

		doc, err := database.GetDocument(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document not found"})
			return
		}

		if !authorizeApplicationAccess(c, db, doc.ApplicationID) {
			return
		}

		if minioStore == nil || minioStore.Client == nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to prepare download"})
			return
		}

		object, err := minioStore.Client.GetObject(c, minioStore.Bucket, doc.FileURL, minio.GetObjectOptions{})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to open document"})
			return
		}
		defer object.Close()

		info, err := object.Stat()
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document file not found"})
			return
		}

		contentType := strings.TrimSpace(derefString(doc.ContentType))
		if contentType == "" {
			contentType = strings.TrimSpace(info.ContentType)
		}
		if contentType == "" {
			contentType = "application/octet-stream"
		}

		filename := strings.TrimSpace(derefString(doc.OriginalFilename))
		if filename == "" {
			filename = filepath.Base(doc.FileURL)
		}

		c.Header("Content-Type", contentType)
		c.Header("Content-Length", strconv.FormatInt(info.Size, 10))
		c.Header("Content-Disposition", fmt.Sprintf("inline; filename=%q", filename))

		if _, err := io.Copy(c.Writer, object); err != nil {
			c.Error(err)
		}
	}
}

//////////////////////////////////////////////////////////
// HOUSING STAFF HANDLERS
//////////////////////////////////////////////////////////

func HousingListApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var yearFilter *int
		if rawYear := strings.TrimSpace(c.Query("year")); rawYear != "" {
			parsedYear, err := strconv.Atoi(rawYear)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid year"})
				return
			}
			yearFilter = &parsedYear
		}

		search := strings.TrimSpace(c.Query("search"))
		if search == "" {
			search = strings.TrimSpace(c.Query("q"))
		}

		apps, err := database.HousingListApplications(db, database.HousingApplicationFilters{
			Status: strings.TrimSpace(c.Query("status")),
			Year:   yearFilter,
			Gender: strings.TrimSpace(c.Query("gender")),
			Major:  strings.TrimSpace(c.Query("major")),
			Search: search,
		})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list applications", "details": err.Error()})
			return
		}
		roomAllocations, err := listRoomAllocationPayloads(db, apps)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch room allocations", "details": err.Error()})
			return
		}
		response := make([]gin.H, 0, len(apps))
		for _, app := range apps {
			response = append(response, buildBasicApplicationPayloadWithRoom(app, "", roomAllocations[app.ID]))
		}
		c.JSON(http.StatusOK, response)
	}
}

func HousingGetApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		app, err := database.HousingGetApplication(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		payload, err := buildApplicationReviewPayload(db, app)
		if err != nil {
			c.JSON(http.StatusOK, buildBasicApplicationPayload(db, app, err.Error()))
			return
		}
		c.JSON(http.StatusOK, payload)
	}
}

func HousingDormInventory(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var blockFilter *int
		if rawBlock := strings.TrimSpace(c.Query("block")); rawBlock != "" {
			parsed, err := strconv.Atoi(rawBlock)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid block"})
				return
			}
			blockFilter = &parsed
		}

		var roomFilter *int
		if rawRoom := strings.TrimSpace(c.Query("room")); rawRoom != "" {
			parsed, err := strconv.Atoi(rawRoom)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid room"})
				return
			}
			roomFilter = &parsed
		}

		search := strings.TrimSpace(c.Query("search"))
		if search == "" {
			search = strings.TrimSpace(c.Query("q"))
		}

		rows, err := database.ListDormInventory(db, database.DormInventoryFilters{
			Block:  blockFilter,
			Room:   roomFilter,
			Gender: strings.TrimSpace(c.Query("gender")),
			Major:  strings.TrimSpace(c.Query("major")),
			Search: search,
		})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list dorm inventory", "details": err.Error()})
			return
		}
		if rows == nil {
			rows = []models.DormInventoryRow{}
		}
		c.JSON(http.StatusOK, rows)
	}
}

func HousingApprove(db *sql.DB, cfg *config.Config) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingApprove(db, id, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "approve failed", "details": err.Error()})
			return
		}

		emailSent := false
		emailSkipped := false
		if cfg != nil {
			recipient, err := database.GetApplicationNotificationRecipient(db, id)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "application approved but notification recipient could not be loaded", "details": err.Error()})
				return
			}

			sender := notifications.NewEmailSender(cfg)
			if !sender.Configured() {
				emailSkipped = true
			} else {
				message := buildApprovedApplicationPaymentEmail(cfg, recipient)
				if strings.TrimSpace(message.To) == "" {
					emailSkipped = true
				} else if err := sender.Send(message); err != nil {
					c.JSON(http.StatusInternalServerError, gin.H{"error": "application approved but approval email could not be sent", "details": err.Error()})
					return
				} else {
					emailSent = true
				}
			}
		}

		c.JSON(http.StatusOK, gin.H{"status": "approved", "email_sent": emailSent, "email_skipped": emailSkipped})
	}
}

func HousingReject(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		var body struct {
			Reason string `json:"reason" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "reason is required"})
			return
		}
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingReject(db, id, body.Reason, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "reject failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "rejected"})
	}
}

//////////////////////////////////////////////////////////
// ADMIN HANDLERS
//////////////////////////////////////////////////////////

func AdminListUsers(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		users, err := database.ListUsers(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list users"})
			return
		}
		c.JSON(http.StatusOK, users)
	}
}

func AdminCreateUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			NuID  string `json:"nu_id" binding:"required"`
			Email string `json:"email" binding:"required,email"`
			Phone string `json:"phone"`
			Role  string `json:"role" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}
		roleID, err := database.GetRoleIDByName(db, body.Role)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role"})
			return
		}
		if _, err := database.GetUserByEmail(db, body.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}
		u := models.User{
			NuID:         body.NuID,
			Email:        strings.ToLower(strings.TrimSpace(body.Email)),
			PasswordHash: "",
			RoleID:       roleID,
			Phone:        &body.Phone,
		}
		id, err := database.CreateUser(db, u)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "create user failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"id": id})
	}
}

func AdminDeleteUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		if err := database.DeleteUser(db, id); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "delete failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "deleted"})
	}
}

func AdminUpdateUserRole(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, err := strconv.Atoi(idStr)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid user id"})
			return
		}

		var body struct {
			Role string `json:"role" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}

		roleID, err := database.GetRoleIDByName(db, body.Role)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role"})
			return
		}

		user, err := database.GetUserByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "user not found"})
			return
		}
		if user.RoleID == roleID {
			c.JSON(http.StatusOK, gin.H{"status": "unchanged"})
			return
		}

		if err := database.UpdateUserRole(db, id, roleID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "role update failed", "details": err.Error()})
			return
		}

		c.JSON(http.StatusOK, gin.H{"status": "updated"})
	}
}

func AdminSystemLogs(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		logs, err := database.AdminSystemLogs(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch logs"})
			return
		}
		c.JSON(http.StatusOK, logs)
	}
}

func AdminStats(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		stats, err := database.AdminStats(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch stats"})
			return
		}
		c.JSON(http.StatusOK, stats)
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLER
//////////////////////////////////////////////////////////

func GetDocumentsByApplication(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("app_id")
		appID, _ := strconv.Atoi(idStr)

		if !authorizeApplicationAccess(c, db, appID) {
			return
		}

		docs, err := database.GetDocumentsByApplication(db, appID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch documents"})
			return
		}

		type DocResponse struct {
			ID                 int      `json:"id"`
			Type               string   `json:"type"`
			Name               string   `json:"name,omitempty"`
			Filename           string   `json:"filename,omitempty"`
			DownloadURL        string   `json:"download_url"`
			Status             string   `json:"status,omitempty"`
			Decision           string   `json:"decision,omitempty"`
			ManualReviewReason string   `json:"manual_review_reason,omitempty"`
			ReviewReason       string   `json:"review_reason,omitempty"`
			Reasoning          string   `json:"reasoning,omitempty"`
			Issues             []string `json:"issues,omitempty"`
			DetectedCategory   string   `json:"detected_category,omitempty"`
		}

		analyses, err := database.ListDocumentAnalysesByApplicationID(db, appID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch document review details", "details": err.Error()})
			return
		}
		analysisByDocumentID := make(map[int]models.DocumentAnalysis, len(analyses))
		for _, analysisRow := range analyses {
			analysisByDocumentID[analysisRow.DocumentID] = analysisRow
		}

		var result []DocResponse
		for _, doc := range docs {
			analysisRow, ok := analysisByDocumentID[doc.ID]
			status := ""
			decision := ""
			manualReviewReason := ""
			reviewReason := ""
			reasoning := ""
			issues := []string{}
			detectedCategory := ""
			if ok {
				status = analysisRow.Status
				decision = analysisRow.Status
				detectedCategory = analysisRow.DetectedCategory
				issues = analysisRow.Issues
				if analysisRow.Status != string(analysis.StatusPassed) {
					reasoning = analysisRow.ReasoningSummary
					reviewReason = analysisRow.ReasoningSummary
				}
				if analysisRow.Status == string(analysis.StatusManualReview) {
					manualReviewReason = analysisRow.ReasoningSummary
				}
			}
			result = append(result, DocResponse{
				ID:                 doc.ID,
				Type:               doc.Type,
				Name:               derefString(doc.OriginalFilename),
				Filename:           derefString(doc.OriginalFilename),
				DownloadURL:        buildDocumentDownloadURL(c, doc.ID),
				Status:             status,
				Decision:           decision,
				ManualReviewReason: manualReviewReason,
				ReviewReason:       reviewReason,
				Reasoning:          reasoning,
				Issues:             issues,
				DetectedCategory:   detectedCategory,
			})
		}

		if result == nil {
			result = []DocResponse{}
		}

		c.JSON(http.StatusOK, result)
	}
}

func buildApplicationReviewPayload(db *sql.DB, app models.Application) (gin.H, error) {
	analyses, err := database.ListDocumentAnalysesByApplicationID(db, app.ID)
	if err != nil {
		return nil, err
	}
	roomAllocation := lookupRoomAllocationPayload(db, app.ID)

	manualReviewReasons := make([]string, 0)
	reviewReasons := make([]string, 0)
	problematicDocuments := make([]gin.H, 0)
	for _, analysisRow := range analyses {
		reason := strings.TrimSpace(analysisRow.ReasoningSummary)
		if reason == "" || analysisRow.Status == string(analysis.StatusPassed) {
			continue
		}

		reviewReasons = append(reviewReasons, fmt.Sprintf("%s: %s", analysisRow.ExpectedType, reason))
		if analysisRow.Status == string(analysis.StatusManualReview) {
			manualReviewReasons = append(manualReviewReasons, fmt.Sprintf("%s: %s", analysisRow.ExpectedType, reason))
		}

		problematicDocuments = append(problematicDocuments, gin.H{
			"document_id":   analysisRow.DocumentID,
			"expected_type": analysisRow.ExpectedType,
			"status":        analysisRow.Status,
			"decision":      analysisRow.Status,
			"manual_review_reason": func() string {
				if analysisRow.Status == string(analysis.StatusManualReview) {
					return reason
				}
				return ""
			}(),
			"review_reason":         reason,
			"reasoning":             reason,
			"issues":                analysisRow.Issues,
			"detected_category":     analysisRow.DetectedCategory,
			"matched_applicant_fio": analysisRow.MatchedApplicantFIO,
			"extracted_fio":         analysisRow.ExtractedFIO,
			"has_astana_property":   analysisRow.HasAstanaProperty,
			"has_astana_residence":  analysisRow.HasAstanaResidence,
			"has_astana_employment": analysisRow.HasAstanaEmployment,
		})
	}

	identity := applicationIdentityPayload(app)
	return gin.H{
		"id":                    app.ID,
		"application_id":        app.ID,
		"user_id":               app.StudentID,
		"student_user_id":       app.StudentID,
		"student_db_id":         app.StudentID,
		"student_id":            identity["student_id"],
		"studentId":             identity["student_id"],
		"applicant_type":        app.ApplicantType,
		"student_number":        identity["student_number"],
		"studentNumber":         identity["student_number"],
		"name_surname":          identity["name_surname"],
		"nameSurname":           identity["name_surname"],
		"fio":                   identity["fio"],
		"name":                  identity["name"],
		"display_name":          identity["name"],
		"displayName":           identity["name"],
		"full_name":             identity["name"],
		"fullName":              identity["name"],
		"student_name":          identity["name"],
		"studentName":           identity["name"],
		"applicant_name":        identity["name"],
		"applicantName":         identity["name"],
		"first_name":            identity["first_name"],
		"firstName":             identity["first_name"],
		"last_name":             identity["last_name"],
		"lastName":              identity["last_name"],
		"student":               identity,
		"applicant":             identity,
		"user":                  identity,
		"birth_date":            app.BirthDate,
		"iin":                   app.IIN,
		"school":                app.School,
		"level":                 app.Level,
		"passport_number":       app.PassportNumber,
		"comments":              app.Comments,
		"year":                  app.Year,
		"major":                 app.Major,
		"gender":                app.Gender,
		"room_preference":       app.RoomPreference,
		"additional_info":       app.AdditionalInfo,
		"status":                app.Status,
		"is_approved":           strings.EqualFold(strings.TrimSpace(app.Status), "approved"),
		"submitted_at":          app.SubmittedAt,
		"updated_at":            app.UpdatedAt,
		"rejected_reason":       app.RejectedReason,
		"decision_reason":       app.DecisionReason,
		"reviewed_by":           app.ReviewedBy,
		"review_timestamp":      app.ReviewTimestamp,
		"manual_review_reasons": manualReviewReasons,
		"review_reasons":        reviewReasons,
		"problematic_documents": problematicDocuments,
		"room_allocation":       roomAllocation,
		"room":                  roomLabelFromPayload(roomAllocation),
		"editable_details":      extractEditableApplicationDetails(app.AdditionalInfo),
	}, nil
}

func buildBasicApplicationPayload(db *sql.DB, app models.Application, reviewDetailsError string) gin.H {
	return buildBasicApplicationPayloadWithRoom(app, reviewDetailsError, lookupRoomAllocationPayload(db, app.ID))
}

func buildBasicApplicationPayloadWithRoom(app models.Application, reviewDetailsError string, roomAllocation gin.H) gin.H {
	manualReviewReasons := []string{}
	reviewReasons := []string{}
	if app.DecisionReason != nil && strings.TrimSpace(*app.DecisionReason) != "" {
		reviewReasons = append(reviewReasons, strings.TrimSpace(*app.DecisionReason))
		if strings.EqualFold(strings.TrimSpace(app.Status), "pending") {
			manualReviewReasons = append(manualReviewReasons, strings.TrimSpace(*app.DecisionReason))
		}
	}
	identity := applicationIdentityPayload(app)
	isPaid := app.PaymentStatus != nil && strings.EqualFold(strings.TrimSpace(*app.PaymentStatus), "paid")
	return gin.H{
		"id":                    app.ID,
		"application_id":        app.ID,
		"user_id":               app.StudentID,
		"student_user_id":       app.StudentID,
		"student_db_id":         app.StudentID,
		"student_id":            identity["student_id"],
		"studentId":             identity["student_id"],
		"applicant_type":        app.ApplicantType,
		"student_number":        identity["student_number"],
		"studentNumber":         identity["student_number"],
		"name_surname":          identity["name_surname"],
		"nameSurname":           identity["name_surname"],
		"fio":                   identity["fio"],
		"name":                  identity["name"],
		"display_name":          identity["name"],
		"displayName":           identity["name"],
		"full_name":             identity["name"],
		"fullName":              identity["name"],
		"student_name":          identity["name"],
		"studentName":           identity["name"],
		"applicant_name":        identity["name"],
		"applicantName":         identity["name"],
		"first_name":            identity["first_name"],
		"firstName":             identity["first_name"],
		"last_name":             identity["last_name"],
		"lastName":              identity["last_name"],
		"student":               identity,
		"applicant":             identity,
		"user":                  identity,
		"birth_date":            app.BirthDate,
		"iin":                   app.IIN,
		"school":                app.School,
		"level":                 app.Level,
		"passport_number":       app.PassportNumber,
		"comments":              app.Comments,
		"year":                  app.Year,
		"major":                 app.Major,
		"gender":                app.Gender,
		"room_preference":       app.RoomPreference,
		"additional_info":       app.AdditionalInfo,
		"status":                app.Status,
		"is_approved":           strings.EqualFold(strings.TrimSpace(app.Status), "approved"),
		"is_paid":               isPaid,
		"paid":                  isPaid,
		"payment_status":        app.PaymentStatus,
		"paid_at":               app.PaidAt,
		"submitted_at":          app.SubmittedAt,
		"updated_at":            app.UpdatedAt,
		"rejected_reason":       app.RejectedReason,
		"decision_reason":       app.DecisionReason,
		"reviewed_by":           app.ReviewedBy,
		"review_timestamp":      app.ReviewTimestamp,
		"manual_review_reasons": manualReviewReasons,
		"review_reasons":        reviewReasons,
		"problematic_documents": []gin.H{},
		"room_allocation":       roomAllocation,
		"room":                  roomLabelFromPayload(roomAllocation),
		"editable_details":      extractEditableApplicationDetails(app.AdditionalInfo),
		"review_details_error":  reviewDetailsError,
	}
}

func listRoomAllocationPayloads(db *sql.DB, apps []models.Application) (map[int]gin.H, error) {
	result := make(map[int]gin.H, len(apps))
	if db == nil || len(apps) == 0 {
		return result, nil
	}

	applicationIDs := make([]int, 0, len(apps))
	for _, app := range apps {
		applicationIDs = append(applicationIDs, app.ID)
	}

	allocations, err := database.ListRoomAllocationsByApplicationIDs(db, applicationIDs)
	if err != nil {
		return nil, err
	}
	for applicationID, allocation := range allocations {
		result[applicationID] = roomAllocationPayload(allocation)
	}
	return result, nil
}

func applicationIdentityPayload(app models.Application) gin.H {
	studentNumber := strings.TrimSpace(app.StudentNumber)
	nameSurname := strings.TrimSpace(app.NameSurname)
	fio := strings.TrimSpace(app.FIO)
	displayName := applicationDisplayName(app)
	firstName, lastName := splitDisplayName(displayName)

	return gin.H{
		"id":             studentNumber,
		"student_id":     studentNumber,
		"studentId":      studentNumber,
		"student_number": studentNumber,
		"studentNumber":  studentNumber,
		"name":           displayName,
		"display_name":   displayName,
		"displayName":    displayName,
		"full_name":      displayName,
		"fullName":       displayName,
		"student_name":   displayName,
		"studentName":    displayName,
		"applicant_name": displayName,
		"applicantName":  displayName,
		"name_surname":   nameSurname,
		"nameSurname":    nameSurname,
		"fio":            fio,
		"first_name":     firstName,
		"firstName":      firstName,
		"last_name":      lastName,
		"lastName":       lastName,
	}
}

func applicationDisplayName(app models.Application) string {
	for _, value := range []string{
		app.NameSurname,
		app.FIO,
		app.StudentNumber,
	} {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func splitDisplayName(displayName string) (string, string) {
	parts := strings.Fields(strings.TrimSpace(displayName))
	if len(parts) == 0 {
		return "", ""
	}
	if len(parts) == 1 {
		return parts[0], ""
	}
	return parts[0], strings.Join(parts[1:], " ")
}

func lookupRoomAllocationPayload(db *sql.DB, applicationID int) gin.H {
	if db == nil {
		return nil
	}
	allocation, err := database.GetRoomAllocationByApplicationID(db, applicationID)
	if err != nil {
		return nil
	}
	return roomAllocationPayload(allocation)
}

func roomAllocationPayload(allocation models.RoomAllocation) gin.H {
	return gin.H{
		"id":             allocation.ID,
		"application_id": allocation.ApplicationID,
		"student_id":     allocation.StudentID,
		"block":          allocation.Block,
		"room_number":    allocation.RoomNumber,
		"bed_number":     allocation.BedNumber,
		"room":           fmt.Sprintf("%d.%d", allocation.Block, allocation.RoomNumber),
		"created_at":     allocation.CreatedAt,
	}
}

func roomLabelFromPayload(payload gin.H) string {
	if payload == nil {
		return ""
	}
	if room, ok := payload["room"].(string); ok {
		return room
	}
	return ""
}

func mergeEditableApplicationDetails(additionalInfo string, apartmentInAstana, parentsWorkInAstana, astanaResident *bool, preferredRoommate *string) string {
	managedKeys := map[string]bool{
		"apartment_in_astana":    true,
		"parents_work_in_astana": true,
		"astana_resident":        true,
		"preferred_roommate":     true,
	}

	lines := make([]string, 0)
	for _, line := range strings.Split(additionalInfo, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		key, _, ok := strings.Cut(trimmed, ":")
		if ok && managedKeys[strings.ToLower(strings.TrimSpace(key))] {
			continue
		}
		lines = append(lines, trimmed)
	}

	if apartmentInAstana != nil {
		lines = append(lines, fmt.Sprintf("apartment_in_astana: %t", *apartmentInAstana))
	}
	if parentsWorkInAstana != nil {
		lines = append(lines, fmt.Sprintf("parents_work_in_astana: %t", *parentsWorkInAstana))
	}
	if astanaResident != nil {
		lines = append(lines, fmt.Sprintf("astana_resident: %t", *astanaResident))
	}
	if preferredRoommate != nil {
		lines = append(lines, "preferred_roommate: "+strings.TrimSpace(*preferredRoommate))
	}

	return strings.Join(lines, "\n")
}

func extractEditableApplicationDetails(additionalInfo string) gin.H {
	details := gin.H{
		"apartment_in_astana":    nil,
		"parents_work_in_astana": nil,
		"astana_resident":        nil,
		"preferred_roommate":     "",
	}

	for _, line := range strings.Split(additionalInfo, "\n") {
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.ToLower(strings.TrimSpace(key))
		value = strings.TrimSpace(value)
		switch key {
		case "apartment_in_astana", "parents_work_in_astana", "astana_resident":
			if parsed, ok := parseBoolDetail(value); ok {
				details[key] = parsed
			}
		case "preferred_roommate":
			details[key] = value
		}
	}

	return details
}

func parseBoolDetail(value string) (bool, bool) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "true", "yes", "1":
		return true, true
	case "false", "no", "0":
		return false, true
	default:
		return false, false
	}
}

func authorizeApplicationAccess(c *gin.Context, db *sql.DB, applicationID int) bool {
	userID, role, ok := requestIdentity(c)
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "missing Authorization header"})
		return false
	}

	if role == "housing" {
		return true
	}

	app, err := database.GetApplicationByID(db, applicationID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
		return false
	}

	if app.StudentID != userID {
		c.JSON(http.StatusForbidden, gin.H{"error": "access denied"})
		return false
	}

	return true
}

func buildDocumentDownloadURL(c *gin.Context, docID int) string {
	userID, role, ok := requestIdentity(c)
	if !ok {
		return ""
	}

	token, err := auth.GenerateTokenWithTTL(userID, role, 15*time.Minute)
	if err != nil {
		return ""
	}

	scheme := "http"
	if c.Request.TLS != nil {
		scheme = "https"
	}
	if forwardedProto := c.GetHeader("X-Forwarded-Proto"); forwardedProto != "" {
		scheme = forwardedProto
	}

	return fmt.Sprintf("%s://%s/documents/%d/download?token=%s", scheme, c.Request.Host, docID, url.QueryEscape(token))
}

func requestIdentity(c *gin.Context) (int, string, bool) {
	if uid, ok := c.Get("user_id"); ok {
		if roleVal, roleExists := c.Get("role"); roleExists {
			return uid.(int), roleVal.(string), true
		}
	}

	tokenStr := strings.TrimSpace(c.Query("token"))
	if tokenStr == "" {
		return 0, "", false
	}

	claims, err := auth.ParseToken(tokenStr)
	if err != nil {
		return 0, "", false
	}

	return claims.UserID, claims.Role, true
}

func derefString(value *string) string {
	if value == nil {
		return ""
	}

	return *value
}

func buildSystemSettingsResponse(settings models.SystemSettings) gin.H {
	return gin.H{
		"id":                   settings.ID,
		"applications_enabled": settings.ApplicationsEnabled,
		"is_application_open":  database.IsApplicationsOpen(settings, time.Now()),
		"application_open":     formatDatePtr(settings.ApplicationOpen),
		"application_close":    formatDatePtr(settings.ApplicationClose),
		"required_documents":   settings.RequiredDocuments,
	}
}

func formatDatePtr(value *time.Time) any {
	if value == nil {
		return nil
	}
	return value.UTC().Format("2006-01-02")
}

func parseDateField(raw string) (*time.Time, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, nil
	}

	parsed, err := time.Parse("2006-01-02", raw)
	if err != nil {
		return nil, err
	}
	date := parsed.UTC()
	return &date, nil
}

type applicationEmailResult struct {
	Sent    int
	Failed  int
	Skipped int
	Errors  []string
}

func sendApplicationClosureEmails(cfg *config.Config, recipients []database.ApplicationNotificationRecipient) applicationEmailResult {
	result := applicationEmailResult{}
	sender := notifications.NewEmailSender(cfg)
	if !sender.Configured() {
		result.Skipped = len(recipients)
		return result
	}

	for _, recipient := range recipients {
		message := buildApplicationClosureEmail(recipient)
		if strings.TrimSpace(message.To) == "" {
			result.Skipped++
			continue
		}
		if err := sender.Send(message); err != nil {
			result.Failed++
			if len(result.Errors) < 10 {
				result.Errors = append(result.Errors, fmt.Sprintf("%s: %v", message.To, err))
			}
			continue
		}
		result.Sent++
	}

	return result
}

func buildApplicationClosureEmail(recipient database.ApplicationNotificationRecipient) notifications.EmailMessage {
	name := strings.TrimSpace(recipient.DisplayName)
	if name == "" {
		name = "Student"
	}

	message := database.ApplicationClosureNotificationMessage(recipient)
	body := fmt.Sprintf("Dear %s,\n\n%s\n\nRegards,\nNU Housing", name, message)

	return notifications.EmailMessage{
		To:      strings.TrimSpace(recipient.Email),
		Subject: "NU Housing application result",
		Body:    body,
	}
}

func buildApprovedApplicationPaymentEmail(cfg *config.Config, recipient database.ApplicationNotificationRecipient) notifications.EmailMessage {
	name := strings.TrimSpace(recipient.DisplayName)
	if name == "" {
		name = "Student"
	}

	paymentURL := fmt.Sprintf(
		"%s/dashboard/student/payment?applicationId=%d",
		strings.TrimRight(cfg.FrontendBaseURL, "/"),
		recipient.ApplicationID,
	)

	body := fmt.Sprintf(
		"Dear %s,\n\nYour housing application has been approved.\n\nTo confirm your place, please complete the housing payment using the link below:\n%s\n\nIf the payment page does not open directly, sign in to the NU Housing portal and open the Payment section for application #%d.\n\nRegards,\nNU Housing",
		name,
		paymentURL,
		recipient.ApplicationID,
	)

	return notifications.EmailMessage{
		To:      strings.TrimSpace(recipient.Email),
		Subject: "NU Housing application approved: payment required",
		Body:    body,
	}
}
