package handlers

import (
	"bytes"
	"context"
	"crypto/rand"
	"database/sql"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/url"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"nu-housing-management-system/backend/internal/analysis"
	"nu-housing-management-system/backend/internal/auth"
	"nu-housing-management-system/backend/internal/database"
	"nu-housing-management-system/backend/internal/models"

	"github.com/gin-gonic/gin"
	"github.com/lib/pq"
	"github.com/minio/minio-go/v7"
	"github.com/spf13/viper"
)

//////////////////////////////////////////////////////////
// AUTH HANDLERS
//////////////////////////////////////////////////////////

func Register(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var user struct {
			NuID            string `json:"nu_id"`
			FirstName       string `json:"firstName"`
			LastName        string `json:"lastName"`
			Email           string `json:"email" binding:"required,email"`
			Password        string `json:"password" binding:"required,min=6"`
			ConfirmPassword string `json:"confirmPassword"`
			Phone           string `json:"phone"`
			Role            string `json:"role"`
		}
		if err := c.ShouldBindJSON(&user); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		if user.ConfirmPassword != "" && user.Password != user.ConfirmPassword {
			c.JSON(http.StatusBadRequest, gin.H{"error": "passwords do not match"})
			return
		}

		role := strings.ToLower(user.Role)
		if role == "" {
			role = "student"
		}

		if role != "student" && role != "housing" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role: only 'student' or 'housing' allowed"})
			return
		}

		nuID := strings.TrimSpace(user.NuID)
		autoGeneratedNuID := nuID == ""
		if autoGeneratedNuID {
			nuID = generateFallbackNuID()
		}

		roleID, err := database.GetRoleIDByName(db, role)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "role lookup failed"})
			return
		}

		if _, err := database.GetUserByEmail(db, user.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}

		hashed, err := auth.HashPassword(user.Password)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to hash password"})
			return
		}

		u := models.User{
			NuID:         nuID,
			Email:        user.Email,
			PasswordHash: hashed,
			RoleID:       roleID,
			Phone:        &user.Phone,
		}
		id := 0
		for attempt := 0; attempt < 20; attempt++ {
			if autoGeneratedNuID && attempt > 0 {
				u.NuID = generateFallbackNuID()
			}

			id, err = database.CreateUser(db, u)
			if err == nil {
				break
			}

			if autoGeneratedNuID {
				if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" && pqErr.Constraint == "users_nu_id_key" {
					continue
				}
			}

			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": err.Error()})
			return
		}
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user", "details": "could not generate a unique student id"})
			return
		}

		// log registration
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'register', 'user', $1)`, id)

		c.JSON(http.StatusCreated, gin.H{"userId": id})
	}
}

func generateFallbackNuID() string {
	const (
		minSubmissionYear = 2018
		maxSubmissionYear = 2024
	)

	yearSpan := int64(maxSubmissionYear - minSubmissionYear + 1)
	yearOffset, err := rand.Int(rand.Reader, big.NewInt(yearSpan))
	if err != nil {
		return "202400000"
	}

	suffix, err := rand.Int(rand.Reader, big.NewInt(100000))
	if err != nil {
		return "202400000"
	}

	year := minSubmissionYear + int(yearOffset.Int64())
	return fmt.Sprintf("%04d%05d", year, suffix.Int64())
}

func Login(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			Email    string `json:"email" binding:"required,email"`
			Password string `json:"password" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}

		user, err := database.ValidateUserCredentials(db, body.Email)
		if err != nil {
			// log failed login — no actor_id since user not found
			db.Exec(`INSERT INTO audit_logs (action, entity) VALUES ('login_failed', 'user')`)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "no such email exists"})
			return
		}

		if err := auth.CheckPassword(user.PasswordHash, body.Password); err != nil {
			// log failed login — we know the user but wrong password
			db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login_failed', 'user', $1)`, user.ID)
			c.JSON(http.StatusUnauthorized, gin.H{"error": "wrong password"})
			return
		}

		roleName, _ := database.GetRoleNameByID(db, user.RoleID)

		token, err := auth.GenerateToken(user.ID, roleName)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "token generation failed"})
			return
		}

		// log successful login
		db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'login', 'user', $1)`, user.ID)

		c.JSON(http.StatusOK, gin.H{
			"token": token,
			"user": gin.H{
				"id":    user.ID,
				"nu_id": user.NuID,
				"email": user.Email,
				"role":  roleName,
				"phone": user.Phone,
			},
		})
	}
}

//////////////////////////////////////////////////////////
// APPLICATION HANDLERS
//////////////////////////////////////////////////////////

func SubmitApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			ApplicantType  string `json:"applicant_type"`
			FIO            string `json:"fio"`
			PassportNumber string `json:"passport_number"`
			Year           int    `json:"year" binding:"required"`
			Major          string `json:"major" binding:"required"`
			Gender         string `json:"gender" binding:"required"`
			RoomPreference string `json:"room_preference"`
			AdditionalInfo string `json:"additional_info"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load application settings", "details": err.Error()})
			return
		}
		if !database.IsApplicationsOpen(settings, time.Now()) {
			c.JSON(http.StatusForbidden, gin.H{
				"error":                "applications are currently closed",
				"applications_enabled": settings.ApplicationsEnabled,
				"application_open":     formatDatePtr(settings.ApplicationOpen),
				"application_close":    formatDatePtr(settings.ApplicationClose),
			})
			return
		}

		app := models.Application{
			StudentID:      studentID,
			ApplicantType:  database.NormalizeApplicantTypeForSubmission(body.ApplicantType, body.AdditionalInfo),
			FIO:            strings.TrimSpace(body.FIO),
			PassportNumber: strings.TrimSpace(body.PassportNumber),
			Year:           body.Year,
			Major:          body.Major,
			Gender:         body.Gender,
			RoomPreference: body.RoomPreference,
			AdditionalInfo: body.AdditionalInfo,
		}
		if app.FIO == "" {
			app.FIO = database.ExtractFIOForSubmission(body.AdditionalInfo)
		}
		if app.PassportNumber == "" {
			app.PassportNumber = database.ExtractPassportNumberForSubmission(body.AdditionalInfo)
		}

		id, err := database.SubmitApplication(db, app)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to submit application", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"application_id": id})
	}
}

func GetMyApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		apps, err := database.GetApplicationsByStudent(db, studentID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch applications", "details": err.Error()})
			return
		}
		response := make([]gin.H, 0, len(apps))
		for _, app := range apps {
			response = append(response, buildBasicApplicationPayload(app, ""))
		}
		c.JSON(http.StatusOK, response)
	}
}

func UpdateMyApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := strconv.Atoi(c.Param("id"))
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application id"})
			return
		}

		var body struct {
			ApartmentInAstana   *bool   `json:"apartment_in_astana"`
			ParentsWorkInAstana *bool   `json:"parents_work_in_astana"`
			AstanaResident      *bool   `json:"astana_resident"`
			PreferredRoommate   *string `json:"preferred_roommate"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "user_id missing in token"})
			return
		}
		studentID := uid.(int)

		app, err := database.GetApplicationByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		if app.StudentID != studentID {
			c.JSON(http.StatusForbidden, gin.H{"error": "access denied"})
			return
		}

		app.AdditionalInfo = mergeEditableApplicationDetails(
			app.AdditionalInfo,
			body.ApartmentInAstana,
			body.ParentsWorkInAstana,
			body.AstanaResident,
			body.PreferredRoommate,
		)

		updated, err := database.UpdateStudentApplicationDetails(db, studentID, app)
		if err != nil {
			if err.Error() == "application not found" {
				c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
				return
			}
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update application", "details": err.Error()})
			return
		}

		payload, err := buildApplicationReviewPayload(db, updated)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch application review details", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, payload)
	}
}

func GetApplicationStatus(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		if err := database.ApplyAutomatedDecision(db, id); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to refresh application status", "details": err.Error()})
			return
		}
		app, err := database.GetApplicationByID(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		c.JSON(http.StatusOK, gin.H{
			"status":          app.Status,
			"reason":          app.DecisionReason,
			"decision_reason": app.DecisionReason,
			"rejected_reason": app.RejectedReason,
		})
	}
}

func GetSystemSettings(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch system settings", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, buildSystemSettingsResponse(settings))
	}
}

func UpdateSystemSettings(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			ApplicationsEnabled *bool     `json:"applications_enabled"`
			ApplicationOpen     *string   `json:"application_open"`
			ApplicationClose    *string   `json:"application_close"`
			RequiredDocuments   *[]string `json:"required_documents"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input", "details": err.Error()})
			return
		}

		settings, err := database.GetSystemSettings(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to load current settings", "details": err.Error()})
			return
		}

		if body.ApplicationsEnabled != nil {
			settings.ApplicationsEnabled = *body.ApplicationsEnabled
		}

		if body.ApplicationOpen != nil {
			parsedDate, err := parseDateField(*body.ApplicationOpen)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_open", "details": "expected YYYY-MM-DD or empty string"})
				return
			}
			settings.ApplicationOpen = parsedDate
		}

		if body.ApplicationClose != nil {
			parsedDate, err := parseDateField(*body.ApplicationClose)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_close", "details": "expected YYYY-MM-DD or empty string"})
				return
			}
			settings.ApplicationClose = parsedDate
		}

		if settings.ApplicationOpen != nil && settings.ApplicationClose != nil && settings.ApplicationClose.Before(*settings.ApplicationOpen) {
			c.JSON(http.StatusBadRequest, gin.H{"error": "application_close must be on or after application_open"})
			return
		}

		if body.RequiredDocuments != nil {
			settings.RequiredDocuments = *body.RequiredDocuments
		}
		if settings.RequiredDocuments == nil {
			settings.RequiredDocuments = []string{}
		}

		settings, err = database.UpdateSystemSettings(db, settings)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update system settings", "details": err.Error()})
			return
		}

		if userID, _, ok := requestIdentity(c); ok {
			db.Exec(`INSERT INTO audit_logs (actor_id, action, entity, entity_id) VALUES ($1, 'update_settings', 'system_settings', $2)`, userID, settings.ID)
		}

		c.JSON(http.StatusOK, buildSystemSettingsResponse(settings))
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLERS
//////////////////////////////////////////////////////////

func UploadDocument(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		applicationID, err := strconv.Atoi(c.PostForm("application_id"))
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid application_id"})
			return
		}

		docType := c.PostForm("type")
		if docType == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "type is required"})
			return
		}

		file, err := c.FormFile("file")
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "file is required"})
			return
		}

		if !strings.EqualFold(filepath.Ext(file.Filename), ".pdf") {
			c.JSON(http.StatusBadRequest, gin.H{"error": "only PDF files are allowed"})
			return
		}

		fileObj, err := file.Open()
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to open file"})
			return
		}
		defer fileObj.Close()

		if !authorizeApplicationAccess(c, db, applicationID) {
			return
		}

		pdfBytes, err := io.ReadAll(fileObj)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to read file"})
			return
		}

		contentType := file.Header.Get("Content-Type")
		if contentType == "" {
			contentType = "application/pdf"
		}

		objectName := fmt.Sprintf("applications/%d/%s.pdf", applicationID, docType)
		_, err = minioStore.Client.PutObject(
			c,
			minioStore.Bucket,
			objectName,
			bytes.NewReader(pdfBytes),
			int64(len(pdfBytes)),
			minio.PutObjectOptions{ContentType: contentType},
		)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to upload to storage", "details": err.Error()})
			return
		}

		originalFilename := file.Filename
		doc := models.Document{
			ApplicationID:    applicationID,
			Type:             docType,
			FileURL:          objectName,
			OriginalFilename: &originalFilename,
			ContentType:      &contentType,
		}
		id, err := database.SaveDocumentReplacingType(db, doc)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to save document into db", "details": err.Error()})
			return
		}

		go processUploadedDocumentAsync(db, applicationID, id, docType, append([]byte(nil), pdfBytes...))
		c.JSON(http.StatusCreated, gin.H{"document_id": id})
	}
}

func processUploadedDocumentAsync(db *sql.DB, applicationID, documentID int, docType string, pdfBytes []byte) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	if err := analyzeAndApplyDecision(ctx, db, applicationID, documentID, docType, pdfBytes); err != nil {
		fmt.Printf("background document analysis failed for application %d document %d: %v\n", applicationID, documentID, err)
	}
}

func analyzeAndApplyDecision(ctx context.Context, db *sql.DB, applicationID, documentID int, docType string, pdfBytes []byte) error {
	expectedType, ok := analysis.NormalizeDocumentType(docType)
	if !ok {
		result := analysis.ManualReviewResult(
			analysis.Request{
				DocumentID: documentID,
				Application: analysis.ApplicationContext{
					ApplicationID: applicationID,
				},
			},
			"",
			fmt.Sprintf("Manual review required because the uploaded document type %q is not supported for automatic Astana checks.", docType),
			"unsupported_document_type",
		)
		if err := database.UpsertDocumentAnalysis(db, result); err != nil {
			return err
		}
		return database.ApplyAutomatedDecision(db, applicationID)
	}

	app, err := database.GetApplicationByID(db, applicationID)
	if err != nil {
		return err
	}
	user, err := database.GetUserByID(db, app.StudentID)
	if err != nil {
		return err
	}

	analyzer := analysis.NewOpenAIAnalyzer(viper.GetString("OPENAI_API_KEY"), viper.GetString("OPENAI_MODEL"))
	req := analysis.Request{
		DocumentID:   documentID,
		ExpectedType: expectedType,
		PDFBytes:     pdfBytes,
		Application: analysis.ApplicationContext{
			ApplicationID:  app.ID,
			StudentID:      app.StudentID,
			StudentEmail:   user.Email,
			StudentNuID:    user.NuID,
			ApplicantType:  app.ApplicantType,
			StudentFIO:     app.FIO,
			PassportNumber: app.PassportNumber,
			Year:           app.Year,
			Major:          app.Major,
			Gender:         app.Gender,
			RoomPreference: app.RoomPreference,
			AdditionalInfo: app.AdditionalInfo,
			SubmittedAt:    app.SubmittedAt,
			UploadTime:     time.Now().UTC(),
		},
	}

	result, analyzeErr := analyzer.AnalyzeDocument(ctx, req)
	if err := database.UpsertDocumentAnalysis(db, result); err != nil {
		return err
	}
	if err := database.ApplyAutomatedDecision(db, applicationID); err != nil {
		return err
	}
	if analyzeErr != nil {
		return nil
	}
	return nil
}

func GetDocument(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("doc_id")
		id, _ := strconv.Atoi(idStr)
		doc, err := database.GetDocument(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document not found"})
			return
		}

		if !authorizeApplicationAccess(c, db, doc.ApplicationID) {
			return
		}

		c.JSON(http.StatusOK, gin.H{
			"id":                doc.ID,
			"application_id":    doc.ApplicationID,
			"type":              doc.Type,
			"original_filename": doc.OriginalFilename,
			"mime_type":         doc.ContentType,
			"uploaded_at":       doc.UploadedAt,
			"download_url":      buildDocumentDownloadURL(c, doc.ID),
		})
	}
}

func DownloadDocument(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("doc_id")
		id, _ := strconv.Atoi(idStr)

		doc, err := database.GetDocument(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document not found"})
			return
		}

		if !authorizeApplicationAccess(c, db, doc.ApplicationID) {
			return
		}

		if minioStore == nil || minioStore.Client == nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to prepare download"})
			return
		}

		object, err := minioStore.Client.GetObject(c, minioStore.Bucket, doc.FileURL, minio.GetObjectOptions{})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to open document"})
			return
		}
		defer object.Close()

		info, err := object.Stat()
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "document file not found"})
			return
		}

		contentType := strings.TrimSpace(derefString(doc.ContentType))
		if contentType == "" {
			contentType = strings.TrimSpace(info.ContentType)
		}
		if contentType == "" {
			contentType = "application/octet-stream"
		}

		filename := strings.TrimSpace(derefString(doc.OriginalFilename))
		if filename == "" {
			filename = filepath.Base(doc.FileURL)
		}

		c.Header("Content-Type", contentType)
		c.Header("Content-Length", strconv.FormatInt(info.Size, 10))
		c.Header("Content-Disposition", fmt.Sprintf("inline; filename=%q", filename))

		if _, err := io.Copy(c.Writer, object); err != nil {
			c.Error(err)
		}
	}
}

//////////////////////////////////////////////////////////
// HOUSING STAFF HANDLERS
//////////////////////////////////////////////////////////

func HousingListApplications(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var yearFilter *int
		if rawYear := strings.TrimSpace(c.Query("year")); rawYear != "" {
			parsedYear, err := strconv.Atoi(rawYear)
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": "invalid year"})
				return
			}
			yearFilter = &parsedYear
		}

		search := strings.TrimSpace(c.Query("search"))
		if search == "" {
			search = strings.TrimSpace(c.Query("q"))
		}

		apps, err := database.HousingListApplications(db, database.HousingApplicationFilters{
			Status: strings.TrimSpace(c.Query("status")),
			Year:   yearFilter,
			Gender: strings.TrimSpace(c.Query("gender")),
			Major:  strings.TrimSpace(c.Query("major")),
			Search: search,
		})
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list applications", "details": err.Error()})
			return
		}
		response := make([]gin.H, 0, len(apps))
		for _, app := range apps {
			response = append(response, buildBasicApplicationPayload(app, ""))
		}
		c.JSON(http.StatusOK, response)
	}
}

func HousingGetApplication(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		app, err := database.HousingGetApplication(db, id)
		if err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
			return
		}
		payload, err := buildApplicationReviewPayload(db, app)
		if err != nil {
			c.JSON(http.StatusOK, buildBasicApplicationPayload(app, err.Error()))
			return
		}
		c.JSON(http.StatusOK, payload)
	}
}

func HousingApprove(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingApprove(db, id, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "approve failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "approved"})
	}
}

func HousingReject(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		var body struct {
			Reason string `json:"reason" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "reason is required"})
			return
		}
		uid, ok := c.Get("user_id")
		if !ok {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "missing user id"})
			return
		}
		reviewerID := uid.(int)

		if err := database.HousingReject(db, id, body.Reason, reviewerID); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "reject failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "rejected"})
	}
}

//////////////////////////////////////////////////////////
// ADMIN HANDLERS
//////////////////////////////////////////////////////////

func AdminListUsers(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		users, err := database.ListUsers(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to list users"})
			return
		}
		c.JSON(http.StatusOK, users)
	}
}

func AdminCreateUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			NuID  string `json:"nu_id" binding:"required"`
			Email string `json:"email" binding:"required,email"`
			Phone string `json:"phone"`
			Role  string `json:"role" binding:"required"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid input"})
			return
		}
		roleID, err := database.GetRoleIDByName(db, body.Role)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "invalid role"})
			return
		}
		if _, err := database.GetUserByEmail(db, body.Email); err == nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "email already used"})
			return
		}
		u := models.User{
			NuID:         body.NuID,
			Email:        strings.ToLower(strings.TrimSpace(body.Email)),
			PasswordHash: "",
			RoleID:       roleID,
			Phone:        &body.Phone,
		}
		id, err := database.CreateUser(db, u)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "create user failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusCreated, gin.H{"id": id})
	}
}

func AdminDeleteUser(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("id")
		id, _ := strconv.Atoi(idStr)
		if err := database.DeleteUser(db, id); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "delete failed", "details": err.Error()})
			return
		}
		c.JSON(http.StatusOK, gin.H{"status": "deleted"})
	}
}

func AdminSystemLogs(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		logs, err := database.AdminSystemLogs(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch logs"})
			return
		}
		c.JSON(http.StatusOK, logs)
	}
}

func AdminStats(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		stats, err := database.AdminStats(db)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch stats"})
			return
		}
		c.JSON(http.StatusOK, stats)
	}
}

//////////////////////////////////////////////////////////
// DOCUMENT HANDLER
//////////////////////////////////////////////////////////

func GetDocumentsByApplication(db *sql.DB, minioStore *database.MinIOStore) gin.HandlerFunc {
	return func(c *gin.Context) {
		idStr := c.Param("app_id")
		appID, _ := strconv.Atoi(idStr)

		if !authorizeApplicationAccess(c, db, appID) {
			return
		}

		docs, err := database.GetDocumentsByApplication(db, appID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch documents"})
			return
		}

		type DocResponse struct {
			ID                 int      `json:"id"`
			Type               string   `json:"type"`
			Name               string   `json:"name,omitempty"`
			Filename           string   `json:"filename,omitempty"`
			DownloadURL        string   `json:"download_url"`
			Status             string   `json:"status,omitempty"`
			Decision           string   `json:"decision,omitempty"`
			ManualReviewReason string   `json:"manual_review_reason,omitempty"`
			ReviewReason       string   `json:"review_reason,omitempty"`
			Reasoning          string   `json:"reasoning,omitempty"`
			Issues             []string `json:"issues,omitempty"`
			DetectedCategory   string   `json:"detected_category,omitempty"`
		}

		analyses, err := database.ListDocumentAnalysesByApplicationID(db, appID)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to fetch document review details", "details": err.Error()})
			return
		}
		analysisByDocumentID := make(map[int]models.DocumentAnalysis, len(analyses))
		for _, analysisRow := range analyses {
			analysisByDocumentID[analysisRow.DocumentID] = analysisRow
		}

		var result []DocResponse
		for _, doc := range docs {
			analysisRow, ok := analysisByDocumentID[doc.ID]
			status := ""
			decision := ""
			manualReviewReason := ""
			reviewReason := ""
			reasoning := ""
			issues := []string{}
			detectedCategory := ""
			if ok {
				status = analysisRow.Status
				decision = analysisRow.Status
				detectedCategory = analysisRow.DetectedCategory
				issues = analysisRow.Issues
				if analysisRow.Status != string(analysis.StatusPassed) {
					reasoning = analysisRow.ReasoningSummary
					reviewReason = analysisRow.ReasoningSummary
				}
				if analysisRow.Status == string(analysis.StatusManualReview) {
					manualReviewReason = analysisRow.ReasoningSummary
				}
			}
			result = append(result, DocResponse{
				ID:                 doc.ID,
				Type:               doc.Type,
				Name:               derefString(doc.OriginalFilename),
				Filename:           derefString(doc.OriginalFilename),
				DownloadURL:        buildDocumentDownloadURL(c, doc.ID),
				Status:             status,
				Decision:           decision,
				ManualReviewReason: manualReviewReason,
				ReviewReason:       reviewReason,
				Reasoning:          reasoning,
				Issues:             issues,
				DetectedCategory:   detectedCategory,
			})
		}

		if result == nil {
			result = []DocResponse{}
		}

		c.JSON(http.StatusOK, result)
	}
}

func buildApplicationReviewPayload(db *sql.DB, app models.Application) (gin.H, error) {
	analyses, err := database.ListDocumentAnalysesByApplicationID(db, app.ID)
	if err != nil {
		return nil, err
	}

	manualReviewReasons := make([]string, 0)
	reviewReasons := make([]string, 0)
	problematicDocuments := make([]gin.H, 0)
	for _, analysisRow := range analyses {
		reason := strings.TrimSpace(analysisRow.ReasoningSummary)
		if reason == "" || analysisRow.Status == string(analysis.StatusPassed) {
			continue
		}

		reviewReasons = append(reviewReasons, fmt.Sprintf("%s: %s", analysisRow.ExpectedType, reason))
		if analysisRow.Status == string(analysis.StatusManualReview) {
			manualReviewReasons = append(manualReviewReasons, fmt.Sprintf("%s: %s", analysisRow.ExpectedType, reason))
		}

		problematicDocuments = append(problematicDocuments, gin.H{
			"document_id":   analysisRow.DocumentID,
			"expected_type": analysisRow.ExpectedType,
			"status":        analysisRow.Status,
			"decision":      analysisRow.Status,
			"manual_review_reason": func() string {
				if analysisRow.Status == string(analysis.StatusManualReview) {
					return reason
				}
				return ""
			}(),
			"review_reason":         reason,
			"reasoning":             reason,
			"issues":                analysisRow.Issues,
			"detected_category":     analysisRow.DetectedCategory,
			"matched_applicant_fio": analysisRow.MatchedApplicantFIO,
			"extracted_fio":         analysisRow.ExtractedFIO,
			"has_astana_property":   analysisRow.HasAstanaProperty,
			"has_astana_residence":  analysisRow.HasAstanaResidence,
			"has_astana_employment": analysisRow.HasAstanaEmployment,
		})
	}

	return gin.H{
		"id":                    app.ID,
		"student_id":            app.StudentID,
		"applicant_type":        app.ApplicantType,
		"fio":                   app.FIO,
		"passport_number":       app.PassportNumber,
		"year":                  app.Year,
		"major":                 app.Major,
		"gender":                app.Gender,
		"room_preference":       app.RoomPreference,
		"additional_info":       app.AdditionalInfo,
		"status":                app.Status,
		"submitted_at":          app.SubmittedAt,
		"updated_at":            app.UpdatedAt,
		"rejected_reason":       app.RejectedReason,
		"decision_reason":       app.DecisionReason,
		"reviewed_by":           app.ReviewedBy,
		"review_timestamp":      app.ReviewTimestamp,
		"manual_review_reasons": manualReviewReasons,
		"review_reasons":        reviewReasons,
		"problematic_documents": problematicDocuments,
		"editable_details":      extractEditableApplicationDetails(app.AdditionalInfo),
	}, nil
}

func buildBasicApplicationPayload(app models.Application, reviewDetailsError string) gin.H {
	manualReviewReasons := []string{}
	reviewReasons := []string{}
	if app.DecisionReason != nil && strings.TrimSpace(*app.DecisionReason) != "" {
		reviewReasons = append(reviewReasons, strings.TrimSpace(*app.DecisionReason))
		if strings.EqualFold(strings.TrimSpace(app.Status), "pending") {
			manualReviewReasons = append(manualReviewReasons, strings.TrimSpace(*app.DecisionReason))
		}
	}
	return gin.H{
		"id":                    app.ID,
		"student_id":            app.StudentID,
		"applicant_type":        app.ApplicantType,
		"fio":                   app.FIO,
		"passport_number":       app.PassportNumber,
		"year":                  app.Year,
		"major":                 app.Major,
		"gender":                app.Gender,
		"room_preference":       app.RoomPreference,
		"additional_info":       app.AdditionalInfo,
		"status":                app.Status,
		"submitted_at":          app.SubmittedAt,
		"updated_at":            app.UpdatedAt,
		"rejected_reason":       app.RejectedReason,
		"decision_reason":       app.DecisionReason,
		"reviewed_by":           app.ReviewedBy,
		"review_timestamp":      app.ReviewTimestamp,
		"manual_review_reasons": manualReviewReasons,
		"review_reasons":        reviewReasons,
		"problematic_documents": []gin.H{},
		"editable_details":      extractEditableApplicationDetails(app.AdditionalInfo),
		"review_details_error":  reviewDetailsError,
	}
}

func mergeEditableApplicationDetails(additionalInfo string, apartmentInAstana, parentsWorkInAstana, astanaResident *bool, preferredRoommate *string) string {
	managedKeys := map[string]bool{
		"apartment_in_astana":    true,
		"parents_work_in_astana": true,
		"astana_resident":        true,
		"preferred_roommate":     true,
	}

	lines := make([]string, 0)
	for _, line := range strings.Split(additionalInfo, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		key, _, ok := strings.Cut(trimmed, ":")
		if ok && managedKeys[strings.ToLower(strings.TrimSpace(key))] {
			continue
		}
		lines = append(lines, trimmed)
	}

	if apartmentInAstana != nil {
		lines = append(lines, fmt.Sprintf("apartment_in_astana: %t", *apartmentInAstana))
	}
	if parentsWorkInAstana != nil {
		lines = append(lines, fmt.Sprintf("parents_work_in_astana: %t", *parentsWorkInAstana))
	}
	if astanaResident != nil {
		lines = append(lines, fmt.Sprintf("astana_resident: %t", *astanaResident))
	}
	if preferredRoommate != nil {
		lines = append(lines, "preferred_roommate: "+strings.TrimSpace(*preferredRoommate))
	}

	return strings.Join(lines, "\n")
}

func extractEditableApplicationDetails(additionalInfo string) gin.H {
	details := gin.H{
		"apartment_in_astana":    nil,
		"parents_work_in_astana": nil,
		"astana_resident":        nil,
		"preferred_roommate":     "",
	}

	for _, line := range strings.Split(additionalInfo, "\n") {
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.ToLower(strings.TrimSpace(key))
		value = strings.TrimSpace(value)
		switch key {
		case "apartment_in_astana", "parents_work_in_astana", "astana_resident":
			if parsed, ok := parseBoolDetail(value); ok {
				details[key] = parsed
			}
		case "preferred_roommate":
			details[key] = value
		}
	}

	return details
}

func parseBoolDetail(value string) (bool, bool) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "true", "yes", "1":
		return true, true
	case "false", "no", "0":
		return false, true
	default:
		return false, false
	}
}

func authorizeApplicationAccess(c *gin.Context, db *sql.DB, applicationID int) bool {
	userID, role, ok := requestIdentity(c)
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "missing Authorization header"})
		return false
	}

	if role == "housing" {
		return true
	}

	app, err := database.GetApplicationByID(db, applicationID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "application not found"})
		return false
	}

	if app.StudentID != userID {
		c.JSON(http.StatusForbidden, gin.H{"error": "access denied"})
		return false
	}

	return true
}

func buildDocumentDownloadURL(c *gin.Context, docID int) string {
	userID, role, ok := requestIdentity(c)
	if !ok {
		return ""
	}

	token, err := auth.GenerateTokenWithTTL(userID, role, 15*time.Minute)
	if err != nil {
		return ""
	}

	scheme := "http"
	if c.Request.TLS != nil {
		scheme = "https"
	}
	if forwardedProto := c.GetHeader("X-Forwarded-Proto"); forwardedProto != "" {
		scheme = forwardedProto
	}

	return fmt.Sprintf("%s://%s/documents/%d/download?token=%s", scheme, c.Request.Host, docID, url.QueryEscape(token))
}

func requestIdentity(c *gin.Context) (int, string, bool) {
	if uid, ok := c.Get("user_id"); ok {
		if roleVal, roleExists := c.Get("role"); roleExists {
			return uid.(int), roleVal.(string), true
		}
	}

	tokenStr := strings.TrimSpace(c.Query("token"))
	if tokenStr == "" {
		return 0, "", false
	}

	claims, err := auth.ParseToken(tokenStr)
	if err != nil {
		return 0, "", false
	}

	return claims.UserID, claims.Role, true
}

func derefString(value *string) string {
	if value == nil {
		return ""
	}

	return *value
}

func buildSystemSettingsResponse(settings models.SystemSettings) gin.H {
	return gin.H{
		"id":                   settings.ID,
		"applications_enabled": settings.ApplicationsEnabled,
		"is_application_open":  database.IsApplicationsOpen(settings, time.Now()),
		"application_open":     formatDatePtr(settings.ApplicationOpen),
		"application_close":    formatDatePtr(settings.ApplicationClose),
		"required_documents":   settings.RequiredDocuments,
	}
}

func formatDatePtr(value *time.Time) any {
	if value == nil {
		return nil
	}
	return value.UTC().Format("2006-01-02")
}

func parseDateField(raw string) (*time.Time, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, nil
	}

	parsed, err := time.Parse("2006-01-02", raw)
	if err != nil {
		return nil, err
	}
	date := parsed.UTC()
	return &date, nil
}
